---
services:
  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    network_mode: bridge
    volumes:
      - /opt/loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
