---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=claim-FhhQAk7soFCXQ5mKZk17
    volumes:
      - /plex/config:/config
      - /media/shows:/media/tvshows
      - /media/movies:/media/movies
      - /media/music:/media/music
      - /media:/media
    restart: unless-stopped
    ports:
      - 32400:32400
