---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /radarr/config:/config
      - /media/movies:/movies
      - /media/movies:/shows
      - /media/incomplete:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
