version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: http://localhost:8080
      CLIENT_ENDPOINT: http://localhost:3000
      SPOTIFY_PUBLIC: 07e1601f812648f3859ddadb823c2bb2
      SPOTIFY_SECRET: /run/secrets/spotify_secret
  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - /your_spotify_db:/data/db

  web:
    container_name: mongo
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: http://localhost:8080

secrets:
  spotify_secret:
    file: /secrets/SPOTIFY_SECRET
