---
services:
  your_spotify:
    image: lscr.io/linuxserver/your_spotify:latest
    container_name: your_spotify
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - APP_URL=http://localhost:8383
      - SPOTIFY_PUBLIC=07e1601f812648f3859ddadb823c2bb2
      - SPOTIFY_SECRET=/run/secrets/spotify_secret
      - CORS=http://localhost:8383,https://localhost:443
      - MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
    ports:
      - 8383:80
      - 443:443
secrets:
  spotify_secret:
    file: /secrets/SPOTIFY_SECRET
